version: "3"
services:
  store.nginx:
    container_name: store.nginx
    hostname: store.nginx
    image: nginx
    restart: always
    volumes:
      - php_sockets:/var/run/sockets:rw
      - ./:/var/www/html:rw
      - ./docker/nginx:/etc/nginx/conf.d:rw
    ports:
      - 32974:80

  store.php:
    container_name: store.php
    hostname: store.php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - php_sockets:/var/run/sockets:rw
      - mysql_sockets:/var/run/mysqld:rw
      - ./:/var/www/html:rw
    environment:
      USER_ID: 1000
      USER_NAME: user

  store.mysql:
    container_name: store.mysql
    hostname: store.mysql
    image: mysql:5.7
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_sockets:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: BRW31Nw3T_G_0YPE
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: DfnOwStGdz--5fox
  adminer:
    image: adminer
    container_name: store.adminer
    restart: always
    hostname: store.adminer
    ports:
      - 8080

volumes:
  php_sockets:
  mysql_data:
  mysql_sockets:

