version: "3"
services:
  store.nginx:
    container_name: store.nginx
    hostname: store.nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api/:/var/www/store/api:rw
      - ./angular/:/var/www/store/angular:rw
      - ./docker/certs:/var/www/store/certs:ro
      - ./docker/nginx/snippets:/etc/nginx/snippets:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:rw
      - ./docker/logs:/var/log/nginx:rw
    ports:
      - 32978:80
      - 32979:4200
      - 443:443

  store.php:
    container_name: store.php
    hostname: store.php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api:/var/www/store/api:rw

  store.angular:
    container_name: store.angular
    hostname: store.angular
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./angular:/var/www/store/angular:rw

  store.mysql:
    container_name: store.mysql
    hostname: store.mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
  store.adminer:
    image: adminer
    container_name: store.adminer
    restart: always
    hostname: store.adminer
    ports:
      - 32980:8080

