<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerESQx3ai\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerESQx3ai/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerESQx3ai.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerESQx3ai\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerESQx3ai\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ESQx3ai',
    'container.build_id' => '5d2e922a',
    'container.build_time' => 1532867441,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerESQx3ai');
